feat: Add RPC getters for all Sets
farcasterxyz/hub pull request #101
Opened 2022-09-09 21:02 UTC by sagar-a16z

## Change Summary

Added RPC APIs for the remaining Sets in the engine. 

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)

2022-09-09 21:47 UTC, pfletcherhill requested changes

2022-09-09 21:47 UTC, pfletcherhill commented on src/engine/index.ts
> +  async getUsers(): Promise<Set<number>> {
This shouldn't be a promise, it returns data synchronously from the signers map:
```
getUsers(): Set<number> {
  return new Set([...this._signers.keys()]);
}
```

2022-09-09 21:47 UTC, pfletcherhill commented on src/engine/index.ts
> +  async getAllCastsByUser(fid: number): Promise<Set<Cast>> {
No async/promise. Looks like this comment applies to all the new methods.

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.test.ts
> +    const verificationClaim: VerificationEthereumAddressClaim = {
Because you're including `aliceEthWallet` in verificationOptions above, you don't need to create `verificationClaim`, `aliceClaimHash`, or `aliceExternalSignature` here. The factory will do it for you. Those were manually set in the engine.verifications test so we could re-use those specifically as part of a slight performance improvement, but they're not relevant (and make the code more complicated) when you're generating a single verification.

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.test.ts
> +    verification = await Factories.VerificationEthereumAddress.create(
If you want a verification add and remove that are unrelated, then only pass `createParams` and `createOptions` in like other message types. The way it's written now, `verificationRemove` will override `verification`, because they have the same external ethereum address and the remove happens later.

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.test.ts
> +    const response = await client.getAllSignerMessagesByUser(aliceFid);
This shouldn't have to be async

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.test.ts
> +  test('get all reactions for Fid', async () => {
Nit: "...for an fid" rather than "...for Fid"

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.ts
> +  GetUsers,
If we don't include any values, the default is that they'll all convert to numbers (i.e. `GetUsers` is really 0). Is that intended?

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.ts
> +        [RPCRequest[RPCRequest.GetUsers]]: new jayson.Method({
I'm a bit confused by the syntax here. Wouldn't `{ [RPCRequest.GetUsers]: ... }` be the same?

2022-09-09 21:47 UTC, pfletcherhill commented on src/network/rpc.ts
> +  async getFids(): Promise<Result<Set<number>, string>> {
`getUsers`?

2022-09-09 21:47 UTC, pfletcherhill commented on src/sets/followSet.ts
> +    return new Set([Array.from(this._adds.values()), Array.from(this._removes.values())].flat());
Simpler syntax: `return new Set([...this._adds.values(), ...this._removes.values()])`

2022-09-09 22:48 UTC, sagar-a16z commented on src/network/rpc.ts
> +        [RPCRequest[RPCRequest.GetUsers]]: new jayson.Method({
`[RPCRequest.GetUsers]` evaluates to the enum value, where I want the enum key here.

2022-09-09 23:11 UTC, sagar-a16z commented on src/engine/index.ts
> +  async getUsers(): Promise<Set<number>> {
I'm just planning for an async storage sometime down the line.

2022-09-09 23:13 UTC, sagar-a16z commented on src/network/rpc.test.ts
> +    const verificationClaim: VerificationEthereumAddressClaim = {
Makes sense. Thank you. I was running into some errors with the Factory default so just copied what was in the Verification tests.

2022-09-09 23:15 UTC, sagar-a16z commented on src/network/rpc.test.ts
> +    const response = await client.getAllSignerMessagesByUser(aliceFid);
This is a RPC call it needs to be async or if we use Jayson without promises it will be a callback.

2022-09-09 23:18 UTC, sagar-a16z commented on src/network/rpc.ts
> +  GetUsers,
Yeah that's intended. It's only being used for its key strings. 

It shouldn'tbe exported though. Just used by the client and server classes internally.

2022-09-10 04:47 UTC, pfletcherhill approved these changes

2022-09-10 05:02 UTC, merged