feat(sync): Merkle trie to keep track messages merged by the engine
farcasterxyz/hub pull request #145
Opened 2022-10-05 04:49 UTC by sanjayprabhu

## Motivation

See https://github.com/farcasterxyz/hub/issues/66. First in a number of PRs that enable hubs to differentially sync with each other.

## Change Summary

Add a MerkleTrie implementation that keeps track of messages merged by the engine

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

This PR adds a merkle trie implementation that just keeps track of messages merged by the engine on gossip message received. A lot of other changes are explicitly out-of-scope to keep changesets small and will be handled in future PRs. In particular, this PR does not handle existing messages already merged into the engine. See https://github.com/farcasterxyz/hub/issues/66 for the implementation plan.

2022-10-05 05:54 UTC, varunsrin reviewed
Left a first pass of comments looking at the implementation, will review with tests tomorrow

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merklesync.ts
> + * from each other and bring them into sync efficiently. See https://github.com/farcasterxyz/hub/issues/66
nit: this link points to a ticket that points to a notion doc, which may not be a good permanent reference.

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.test.ts
> +    const shuffledIds = syncIds.sort((a, b) => 0.5 - Math.random());
nit: use _a and _b to make the linter stop complaining

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.ts
> +
nit: should filename be `merkleTrie` to stay consistent with capitalization?

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.ts
> + * SyncId represent the unique id of a message in the sync protocol.
this makes it sound like the reason we are combining the hash and timestamp is to get a unique id, which is a bit misleading since we know hash is unique.

i believe the reason we are doing it is to get a key that is both unique and lexicographically causally ordered?

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.ts
> +    return Math.floor(this._timestamp / 1000)
worth explaining the "why" with a comment since the purpose here is not immediately obvious

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.ts
> +  public insert(key: string, value: string, current_index = 0) {
is this guaranteed to return a boolean? i think i see some code paths where it might return undefined which might be confusing to interpret vs false

can test this by defining a return signature here and seeing if typechecker fails

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.ts
> +      if (this._children.has(char) && this._children.get(char)?.value === value) {
might be worth adding a comment saying "this is a duplicate key-value"

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merkletrie.ts
> +    const success = this._children.get(char)?.insert(key, value, current_index + 1);
add comment explaining the case - there is a child node with the character specified but it does not contain the value so we insert it (or something like that)

2022-10-05 05:54 UTC, varunsrin commented on src/sync/merklesync.ts
> +class MerkleSync {
Is the intended class relationship `Hub` owns `MerkleSync` owns `Engine` ? 

MerkleSync feels like a different naming convention, perhaps we should call it the SyncEngine vs CRDT Engine?

2022-10-07 06:08 UTC, varunsrin requested changes

2022-10-07 06:08 UTC, varunsrin commented on src/sync/merkletrie.ts
> +  constructor(message: Message) {
if i were to somehow pass a message that had arbitrary data (by accidentally casting to any and recasting to message) is it possible to permanently bork sync? 

it could create an "unfetachable entry" and the two nodes would never coalesce. i'm not sure if we can 100% defend against such a case, but sanitizing inputs (even when typed) might prevent some errors

2022-10-07 06:08 UTC, varunsrin commented on src/sync/merkletrie.ts
> +      return undefined;
this branch isn't covered by a test case, which may be worth doing

2022-10-07 06:08 UTC, varunsrin commented on src/sync/merkletrie.ts
> +    return undefined;
this branch isn't covered by a test case, which may be worth doing

2022-10-07 23:18 UTC, sanjayprabhu commented on src/sync/merklesync.ts
> +class MerkleSync {
Discussed in person, will be recorded in a doc you're creating.

2022-10-07 23:19 UTC, sanjayprabhu commented on src/sync/merkletrie.ts
> +  public insert(key: string, value: string, current_index = 0) {
Good catch

2022-10-07 23:22 UTC, sanjayprabhu commented on src/sync/merklesync.ts
> + * from each other and bring them into sync efficiently. See https://github.com/farcasterxyz/hub/issues/66
What's a good place to move the notion doc to? The protocol spec? A docs directory inside this repo?

2022-10-07 23:23 UTC, sanjayprabhu commented on src/sync/merkletrie.test.ts
> +    test('timestamp is correct', () => {
Testing agains the factory felt more robust long term, but I did add one test with specific strings for clarity.

2022-10-07 23:27 UTC, sanjayprabhu commented on src/sync/merkletrie.ts
> +  constructor(message: Message) {
Yes, that can happen. The real fix for that is to be able to repair/recreate the trie from the db which will be implemented down the line. 

For now, I did add validation in the constructor to make sure the hashes conform to what we expect. The timestamp is harder to validate since any number is theoretically valid, but added a conservative length check. Together, they should be sufficient protection (but could cause a potential hard hub crash in case we get bad data).

2022-10-07 23:48 UTC, varunsrin approved these changes

2022-10-07 23:49 UTC, merged