Fix and suppress eslint security warnings
farcasterxyz/hub pull request #262
Opened 2022-12-05 08:59 UTC by TimDaub

hey, so I tried adressing #163. Here's the current left-over output of yearn lint

```
yarn lint
yarn run v1.22.18
warning package.json: License should be a valid SPDX license expression
$ eslint  src/ --color --ext .ts

/Users/timdaub/Projects/farcaster/hub/src/urls/chainAccountUrl.ts
  35:30  warning  Found non-literal argument to RegExp Constructor  security/detect-non-literal-regexp

✖ 1 problem (0 errors, 1 warning)
```

I'll comment inline of this PR to document some of the decisions I took.

2022-12-05 09:00 UTC, TimDaub commented on src/network/sync/merkleTrie.ts
> +      // eslint-disable-next-line security/detect-object-injection
`i` is controlled by the for loop, so not dangerous

2022-12-05 09:01 UTC, TimDaub commented on src/network/sync/syncEngine.ts
>        ourSnapshot.excludedHashes.every((value, index) => value === excludedHashes[index]);
`index` is controlled by `every`

2022-12-05 09:02 UTC, TimDaub commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
honestly, I'm not a big fan of using `parseInt` here. What are alternatives?

2022-12-05 09:03 UTC, TimDaub commented on src/storage/db/binaryrocksdb.ts
> +          // eslint-disable-next-line security/detect-non-literal-fs-filename
it seems that eslint is falsely matching this one, as `this._db.open` isn't `fs.open`.

2022-12-05 09:05 UTC, TimDaub commented on src/test/perf/scenario.ts
> -  // safe to disable here since `event` is validated above
IMO it's misleading to document why eslint can be disabled. For safety, it's better if anyone looking at this code interprets it at the time of inspection. Otherwise, this comment may serve as an excuse to not thoroughly inspect the code.

2022-12-05 09:05 UTC, TimDaub commented on src/test/perf/scenario.ts
> +    // eslint-disable-next-line security/detect-object-injection
Moved eslint disable statement such that it caught the warning again.

2022-12-05 09:06 UTC, TimDaub commented on src/urls/utils.ts
> +    // eslint-disable-next-line security/detect-object-injection
`index` is controlled by `forEach`

2022-12-05 09:07 UTC, TimDaub commented on src/urls/utils.ts
> +  // NOTE: Please don't call this function with a user-controlled `spec`
this isn't great, I have to say.

2022-12-05 21:48 UTC, msoica commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
`public insert(key: string, value: string, current_index: number = 0): boolean ` ?

2022-12-05 21:49 UTC, TimDaub commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
I remember that I tried that (adding :number to current_index) but the eslint warning persisted

2022-12-05 21:50 UTC, TimDaub commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
Also, technically can't Typescript infer from "= 0" that it must be a number?

2022-12-06 23:22 UTC, varunsrin commented on src/utils/crypto.ts
> +        // eslint-disable-next-line
can you disable the specific rule as you did on line 31?

2022-12-06 23:22 UTC, varunsrin commented on src/urls/utils.ts
> +    // eslint-disable-next-line
can you disable the specific rule as you did on line 31?

2022-12-06 23:26 UTC, varunsrin commented
@TimDaub great work so far, would you mind adding a comment above every disable explaining why its safe to disable? You've added the descriptions in the PR, but it is useful to have side by side in the code so that a future reader can easily understand why a decision was made, and evaluate if it still holds true.

2022-12-06 23:31 UTC, varunsrin requested changes

2022-12-06 23:31 UTC, varunsrin commented on src/network/p2p/connectionFilter.ts
> +  denyOutboundEncryptedConnection = async (peerId: PeerId): Promise<boolean> => {
the calls to these new method signatures in connectionFilter.test.ts are broken since they pass in two arguments instead of one

2022-12-06 23:31 UTC, varunsrin commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
what is the specific error that eslint is unhappy about?

2022-12-07 16:15 UTC, TimDaub commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
```
/Users/timdaub/Projects/farcaster/hub/src/network/sync/trieNode.ts
  49:18  warning  Variable Assigned to Object Injection Sink  security/detect-object-injection

```

2022-12-07 16:19 UTC, TimDaub commented
> @TimDaub great work so far, would you mind adding a comment above every disable explaining why its safe to disable? You've added the descriptions in the PR, but it is useful to have side by side in the code so that a future reader can easily understand why a decision was made, and evaluate if it still holds true.

ok

2022-12-07 16:21 UTC, TimDaub commented on src/network/p2p/connectionFilter.ts
> +  denyOutboundEncryptedConnection = async (peerId: PeerId): Promise<boolean> => {
ok so instead of removing the beforehand-assumed "unnecessary" argument options, rather we should suppress the warning?

2022-12-07 16:28 UTC, TimDaub commented on src/test/perf/scenario.ts
> +    // eslint-disable-next-line security/detect-object-injection
@varunsrin I think actually that the eslint checking for a security issue like detect object injection in a test file is really unnecessary as the test environment is controlled by the developer and at their own risk. Shall I check if it's possible to disable security/detect-object-injection for the entire `test` directory?

2022-12-07 16:55 UTC, TimDaub commented on src/network/sync/merkleTrie.ts
> +      // eslint-disable-next-line security/detect-object-injection
added comment

2022-12-07 16:56 UTC, TimDaub commented on src/network/sync/trieNode.ts
> +    const char = key[parseInt(current_index, 10)];
I reverted `parseInt` as it failed the tests.

2022-12-07 16:56 UTC, TimDaub commented on src/storage/db/rocksdb.ts
> +          // eslint-disable-next-line security/detect-non-literal-fs-filename
added comment in the code.

2022-12-07 16:57 UTC, TimDaub commented on src/urls/chainUrl.ts
> +      // eslint-disable-next-line security/detect-non-literal-regexp
added comment in code

2022-12-07 16:57 UTC, TimDaub commented
> @TimDaub great work so far, would you mind adding a comment above every disable explaining why its safe to disable? You've added the descriptions in the PR, but it is useful to have side by side in the code so that a future reader can easily understand why a decision was made, and evaluate if it still holds true.

Done.

2022-12-07 16:58 UTC, TimDaub commented
<img width="858" alt="Screenshot 2022-12-07 at 17 58 15" src="https://user-images.githubusercontent.com/2758453/206242375-d4d111c7-ae9f-4b1c-ba95-ba6b05a4c004.png">

I'm confused, I didn't close the PR...

2022-12-07 16:59 UTC, TimDaub commented
Damn I think it's because Github doesn't recognize the newly forced pushed commit :/

2022-12-14 16:54 UTC, varunsrin commented
@sagar-a16z do you want to quickly review the changes to the sync and see if you are OK with them?

@TimDaub i think we're ready to merge once conflicts are resolved

2022-12-14 21:06 UTC, sagar-a16z commented
Sync and p2p related changes look good 👍

2023-01-11 17:37 UTC, closed without merging