fix: remove race condition from SyncEngine test
farcasterxyz/hub pull request #279
Opened 2022-12-09 03:47 UTC by adaddeo

## Motivation

A race condition existed in a SyncEngine test that caused it to fail ~1/10 of the time.

## Change Summary

Used the [Jest Fake Timers API](https://jestjs.io/docs/jest-object#fake-timers) to fudge the time such that the test would never run into the race condition where a change in a higher order digit resulted in messages within the same sync threshold to still result in divergent snapshots.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

This edge case can be repro'd 100% of the time with `jest.setSystemTime(Math.ceil(Date.now() / 100_000) * 100_000);`.

2022-12-09 03:49 UTC, adaddeo commented
feel free to edit my comment, that was my best attempt being newly acquainted with the algorithm

2022-12-13 23:44 UTC, varunsrin requested changes

2022-12-13 23:44 UTC, varunsrin commented on src/network/sync/syncEngine.test.ts
> +    jest.setSystemTime(Math.ceil(Date.now() / 100_000) * 100_000 + 50_000);
can you explain why the specific limits of 100_000 and 50_000 are chosen here?

2022-12-13 23:44 UTC, varunsrin commented on src/network/sync/syncEngine.test.ts
> +     * When the time elapsed between two messages causes a change in a higher
doesn't this indicate a bug in the sync logic itself? that is, we should not be triggering the sync but we will be and this change just suppresses the test

2022-12-13 23:45 UTC, varunsrin commented
there is also another test `differentialSync › sync converges even if signer removal is not within sync threshold` that might require a similar fix

2022-12-14 15:50 UTC, adaddeo commented on src/network/sync/syncEngine.test.ts
> +     * When the time elapsed between two messages causes a change in a higher
after another look I think this should be considered bug

the root cause is that within excludedHashes there are two representations of if a trie has no excluded items at a specified path, either `hash(null)` if a node exists and there are no excluded items or no value if the node doesn't exist

in this test, when the snapshot timestamp ends in `00` seconds, messages merged a few seconds before and a few seconds after will be inserted on different branches

snapshot A has value 099, excludedHashes for prefix 10 is [hash(0)]
snapshot B has values 099 and 101, excludedHashes for prefix 10 is [hash(0), hash(null)]

a sync is triggered even though there is no difference in excluded items for the tries along the prefix

possible solutions:
- excludedHashes contains a value for every index of the prefix (`len(excludedHashes) === len(prefix)`), whether the full path exists or not (e.g. pad with "empty hash" value if a path terminates before the prefix ends)
- leave excludedHashes as is but when comparing excludedHashes take into account that no item at an index represents no excluded items

in my /very humble/ opinion the first solutions seems easier to reason about since it provides explicit values and theres something nice about the `len(excludedHashes) === len(prefix)` invariant. a downside is extra data needs to be sent, but as the trees becomes less sparse this will matter less. could optimize what value represents empty, null instead of hash(null).

interested to hear thoughts of you or someone w/ a deeper understanding than me

2022-12-14 16:49 UTC, varunsrin commented on src/network/sync/syncEngine.test.ts
> +     * When the time elapsed between two messages causes a change in a higher
ok, im actually thinking through some other sync design problems today which may or may get rid of this logic anyway. let's hit pause on this until i'm done with the doc and revisit. 

thanks for investigating and finding this, i'll update the ticket to indicate that it's a bug

2022-12-14 21:13 UTC, varunsrin commented
cc @adityapk00 who is working on sync

2023-01-17 05:14 UTC, pfletcherhill commented
Should this PR still be open?

2023-01-17 05:31 UTC, varunsrin commented
i think it can be closed, but will defer to @adaddeo

2023-01-17 16:09 UTC, adityapk00 commented
I think this can be closed

2023-01-17 16:31 UTC, adaddeo commented
@adityapk00  the test is still in the codebase but commented out, do you want me to remove it?

2023-01-17 16:48 UTC, adityapk00 commented
Yes, probably a good idea to remove the commented out test. 

The syncEngine now depends on gossip to catch up to messages that are <10s old, so this test is not needed any more.

2023-01-17 16:49 UTC, closed without merging