chore(shared-prettier-config)
farcasterxyz/hub pull request #348
Opened 2023-01-01 07:59 UTC by Pavan-Nambi

Prettier configuration is extracted to a shared package and imported into each workspace

## Motivation

https://github.com/farcasterxyz/hub/issues/344#issue-1515272819

## Change Summary

made new prettier config package and imported it into flatbuffers

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

2023-01-02 02:57 UTC, varunsrin reviewed
Thanks for the PR! Two issues that will need to be addressed in addition to the comments: 

1. I noticed this PR added a `package-lock.json` which means you may be using a different package manager. Can you use yarn instead so we don't need this large diff?

2. The commits aren't signed, so Github won't permit a merge. Please see the contributing.md doc in the repo for instructions on how to get that working correctly.

2023-01-02 02:57 UTC, varunsrin commented on packages/flatbuffers/tsconfig.json
> +  //baseUrl is  ./src so..
i'm not sure i understand this comment, what does it mean?

2023-01-02 02:57 UTC, varunsrin commented on packages/prettier-config-custom/index.json
> +{
does an index.json export work when you test it? i've typically only seem them as index.ts with a modules.export on top.

2023-01-02 02:57 UTC, varunsrin commented on packages/tsconfig-custom/base.json
> +{
same comment about json, we should do the same thing that we do with the eslint package

2023-01-02 05:14 UTC, Pavan-Nambi commented on packages/flatbuffers/tsconfig.json
> +  //baseUrl is  ./src so..
i was checking path for config file there i wrote for myself forgot to remove.. sorry will remove it

2023-01-02 05:15 UTC, Pavan-Nambi commented on packages/prettier-config-custom/index.json
> +{
acc to prettier docs it said so hmm ya i will update it with modules.export into a js file

2023-01-02 05:18 UTC, Pavan-Nambi commented on packages/tsconfig-custom/base.json
> +{
for shared tsconfig i only saw using json...  and extending it on tsconfg.json
i will look into bit further ig thankyou for input

2023-01-02 07:20 UTC, Pavan-Nambi commented on packages/prettier-config-custom/index.json
> +{
i have referred multiple projects regarding sharing tsconfig in all projects i have seen so far its done using either making a .json file and extending wherever needed... 
i am not sure how else this should be done can you show me some reference if possible?
ya eslint and prettier we can use modules.export but idk about tsconfig...

2023-01-02 07:21 UTC, Pavan-Nambi commented on packages/prettier-config-custom/index.json
> +{
apologies if i have made any inconvenience i am bit new to open source....

2023-01-03 05:27 UTC, varunsrin commented on packages/prettier-config-custom/index.js
> +module.exports = {};
there doesn't seem to be any config anymore?

2023-01-03 05:27 UTC, varunsrin commented on packages/prettier-config-custom/index.json
> +{
i was referring to prettier here. 

the prettier config can probably be set up similar to eslint-config-custom in this repo, which uses a .js file 

the tsconfig as you said should probably have a json config, as defined here: https://turbo.build/repo/docs/handbook/linting/typescript

2023-01-03 05:29 UTC, varunsrin requested changes

2023-01-03 05:29 UTC, varunsrin commented on packages/flatbuffers/tsconfig.json
> +  "extends": "../tsconfig-custom/tsconfig.json",
we should be able to reference it via package name since it is added as a dependency. using a path makes it more brittle. see this guide: https://turbo.build/repo/docs/handbook/linting/typescript

2023-01-03 06:47 UTC, Pavan-Nambi commented on packages/flatbuffers/tsconfig.json
> +  "extends": "../tsconfig-custom/tsconfig.json",
ok

2023-01-03 06:51 UTC, Pavan-Nambi commented
hey and if you are free can you say what causes bin script confusion... thats the reason i reverted changes at first i tried googling but it just said due to changing bin to package.json but i haven't actually done anything of tht sort
and its saying its a high security threat soo what exactly caused it here..? or normally what sort of thing causes bin script confusion?

https://socket.dev/blog/npm-bin-script-confusion

2023-01-04 17:29 UTC, varunsrin commented
that may have been a problem introduced because you had the npm package lock checked in which retriggered some checks, it seems resolved now

2023-01-04 17:32 UTC, varunsrin requested changes
added a few comments. can you also test that it works correctly across all repos? 

a simple test would involving changing something (like printwidth) in the shared config, running prettier and making sure that all the code across all repos would change. 

similarly, we should check that the tsconfig is also inherited correctly.

2023-01-04 17:32 UTC, varunsrin commented on packages/flatbuffers/package.json
> +    "prettier-config-custom": "*",
it appears that the custom configs for prettier and ts-config are only used by the flatbuffers package. we'll also need to do this for the primary app package

2023-01-04 17:32 UTC, varunsrin commented on packages/prettier-config-custom/index.js
> +  arrowParens: "always",
let's not introduce new configuration here - this should just be a copy of the current prettier config

2023-01-04 17:55 UTC, Pavan-Nambi commented on packages/flatbuffers/package.json
> +    "prettier-config-custom": "*",
oh yaa got it

2023-01-15 19:46 UTC, varunsrin commented
@Pavan-Nambi still planning to finish this? had a few people asking to pick this up, if youre no longer able to work on it

2023-01-30 18:14 UTC, varunsrin commented
closing for now,

2023-01-30 18:14 UTC, closed without merging