Verifications implementation v1
farcasterxyz/hub pull request #35
Opened 2022-07-15 18:27 UTC by pfletcherhill

Implements verifications according to Proposal A' in this notion doc: https://pfletcherhill.notion.site/Reconciling-Verification-and-Signer-message-schema-53e262b6aca74b0da6ecde8836bce828

2022-07-15 18:31 UTC, pfletcherhill commented on src/simulator/basicSimulator.ts
>    async generateMessages(client: Client) {
I only added a verification to the basic simulator. Should I try adding them to others too?

2022-07-15 20:11 UTC, varunsrin commented on src/utils.ts
> -export const signSecp256k1 = (text: string, key: utils.SigningKey): string => {
im probably going to use it to simulate signing from custody addresses, so i asked zach to leave it in there

2022-07-15 21:04 UTC, pfletcherhill commented on src/utils.ts
> -export const signSecp256k1 = (text: string, key: utils.SigningKey): string => {
Okay, I'll re-add.

Practically speaking though, a custody address is an ethereum address, so would it ever sign using this method instead of an EIP 191 supported approach?

2022-07-16 04:06 UTC, varunsrin commented on src/simulator/index.ts
> +        // TODO: decide how to handle unknown message type
if it's typed as a Message, and the branches cover all sub-types of messages, aren't we guaranteed that this won't happpen?

2022-07-16 04:06 UTC, varunsrin commented on src/sets/verificationsSet.ts
> +      return err('VerificationsSet.add: verification was deleted');
nit: "is already deleted" to match the language below

2022-07-16 13:39 UTC, pfletcherhill commented on src/client.ts
> +      } as FC.RootBody,
No, you don't, you're right. Will clean these up.

2022-07-16 16:25 UTC, pfletcherhill commented on src/client.ts
> +    } as FC.VerificationClaim);
This method returns a promise of the hash of the verification claim (not the claim object), but I can remove the `as FC.VerificationClaim`.

2022-07-16 16:33 UTC, pfletcherhill commented on src/client.ts
> +    return message as FC.VerificationAdd;
When I remove this typescript complains with `Message<Body> is not assignable to type `VerificationAdd`. Because `makeMessage` returns `Promise<FC.Message<FC.Body>>`, I think I have to be explicit about `FC.VerificationAdd` here. Do you have another idea/recommendation?

2022-07-16 16:34 UTC, pfletcherhill commented on src/client.ts
> +        externalSignatureType: 'secp256k1-eip-191',
I added it to [this PR](https://github.com/farcasterxyz/protocol/pull/16), though do you want me to write it in notion too?

2022-07-16 16:38 UTC, pfletcherhill commented on src/simulator/index.ts
> +        // TODO: decide how to handle unknown message type
At this moment, yeah. But I think it's still good practice to have some sort of comment here for when new message types are added and we haven't updated this function yet.

2022-07-16 16:42 UTC, pfletcherhill commented on src/client.ts
> +    return message as FC.VerificationRemove;
See reply above

2022-07-16 21:08 UTC, varunsrin requested changes

2022-07-16 21:11 UTC, varunsrin commented on src/client.ts
> +        externalSignatureType: 'secp256k1-eip-191',
nope, that's good enough

2022-07-16 21:12 UTC, varunsrin commented on src/client.ts
> +    return message as FC.VerificationAdd;
ah i forgot that returned a less concrete type, this is fine

2022-07-16 21:13 UTC, varunsrin commented on src/sets/verificationsSet.ts
> +    if (this._adds.get(message.hash)) {
Your solution seems better than mine since it doesn't cause state divergence. 

But is there a way we can extend your solution to avoid duplicates? That would be a much better experience for clients and also stop people from accidentally flooding their hubs with multiple proofs.

2022-07-16 21:14 UTC, varunsrin commented on src/simulator/basicSimulator.ts
>    async generateMessages(client: Client) {
i think we should add them to all, though you can do it in a followup PR if you prefer.

2022-07-16 21:26 UTC, varunsrin commented
we should also wait for @sds to review before merging this in.

2022-07-17 03:33 UTC, pfletcherhill commented on src/sets/verificationsSet.ts
> +    if (this._adds.get(message.hash)) {
Implemented a potential solution here: https://github.com/farcasterxyz/hub/pull/35/commits/cd51cfef44cb7bcfcbd00165bc6301d44f03fcb4

Summary:
* Use `claimHash` as index for both adds and deletes sets
* Prevents duplicate claims (i.e. verifications of same address)
* Hides external address once deleted because `VerificationRemove` only contains hash
* Updated set `add` and `delete` logic to check `signedAt` timestamp and give preference to latest add or delete
* User can still add a verification, delete it, then re-add the same address later on

Only downside I can think of is that the address isn't as hidden as it would be if deletes were indexed by the message hash, because someone with the address could hash it and check the set.

2022-07-17 04:03 UTC, pfletcherhill commented on src/sets/verificationsSet.ts
> +    if (!isVerificationAdd(message)) {
Fair, I'll remove it

2022-07-17 05:34 UTC, varunsrin approved these changes
Left minor comments, LGTM otherwise

2022-07-17 05:34 UTC, varunsrin commented on src/sets/verificationsSet.ts
> +    const {
nit: since we only really need claimHash, signedAt and message, would it be easier to read if we avoided destructuring and instead did something like 

```
const claimHash = message.data.body.claimHash
const signedAt = message.data.signedAt
...
```

2022-07-17 05:34 UTC, varunsrin commented on src/sets/verificationsSet.test.ts
> +      describe('with same timestamp', () => {
is it possible to get a claim with the same timestamp, same claim hash and a different hash?

2022-07-17 16:12 UTC, sds reviewed
Looking great so far. Minor comments/questions inline.

2022-07-17 16:12 UTC, sds commented on src/engine/index.ts
> +  getAllVerificationClaimHashes(username: string): string[] {
Where do we see this method and `getVerificationClaimHashes` being used in practice?

2022-07-17 16:12 UTC, sds commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
I might be missing something, but we're not actually implementing EIP 191 signatures in this PR, right? (i.e. we're not [prepending with `0x19`](https://eips.ethereum.org/EIPS/eip-191#specification) etc.)

What does storing signatures in EIP 191 get us? I realize the spec is short and I have done a cursory read, but curious how you're thinking about its usage here.

2022-07-17 18:29 UTC, pfletcherhill commented on src/simulator/basicSimulator.ts
>    async generateMessages(client: Client) {
Yeah, I'll do a separate simulation PR.

2022-07-17 18:36 UTC, varunsrin commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
I'll let @pfletcherhill address the first question. 

For the second one, mist wallets generate EIP-191 signatures if I'm not mistaken. So we will *have* to assume that they are in that form.

2022-07-17 18:37 UTC, pfletcherhill commented on src/client.ts
> +        type: 'like' as const,
Because `ReactionBody.type` in this case (or anytime we have a `schema` attribute) is a string literal type. So we have to reassure typescript that a variable like this one won't change by adding `as const`.

2022-07-17 18:45 UTC, pfletcherhill commented on src/engine/index.ts
> +  getAllVerificationClaimHashes(username: string): string[] {
I initially added these methods because other sets had similar methods elsewhere in the engine. But I'd imagine that these would be useful for a client to list the ethereum addresses that an account has verified. They'd get all the claim hashes via `getVerificationClaimHashes` and then map over them with `getVerification` to get the addresses.

2022-07-17 18:49 UTC, pfletcherhill commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
I thought the `signMessage` and `verifyMessage` methods from ethers (which we're using) did implement EIP 191. But I'll look into that and confirm.

2022-07-17 18:53 UTC, pfletcherhill commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
The goal for using EIP 191 is to support as many external Ethereum wallets as possible. I think most wallets support EIP 191 now, so if we use the same standard for verifying the external signature we can avoid worrying about which wallet the user has for their external address.

2022-07-17 19:02 UTC, pfletcherhill commented on src/sets/verificationsSet.test.ts
> +      describe('with same timestamp', () => {
Hmm the only reason I can think of would be the account signs the same claim using two different external wallets, which implement different versions of EIP 191. So there may be two valid yet different `externalSignature` values.

2022-07-17 19:05 UTC, pfletcherhill commented on src/sets/verificationsSet.ts
> +    const {
We use `message.hash` as well, so it would be three lines. I prefer destructuring, but it's up to you.

2022-07-17 19:32 UTC, varunsrin commented on src/sets/verificationsSet.ts
> +    const {
no strong opinion here, will resolve

2022-07-18 18:38 UTC, pfletcherhill commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
Upon further investigation, ethers (and every major wallet) implements EIP 191 version `0x45` (i.e. prepending `"\x19Ethereum Signed Message:\n" + len(message)` before signing the message). EIP 191 versions `0x00` and `0x01` are different, and ethers does not support those in `verifyMessage`. So I suggest we change this type to `eip-191-0x45` or `eip-191-personal-sign` to be extra clear. @varunsrin or @sds, have a preference?

2022-07-18 18:42 UTC, varunsrin commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
no strong preference, but slight lean towards 0x45 for precision

2022-07-18 19:28 UTC, sds commented on src/engine/index.ts
> +    if (externalSignatureType !== 'secp256k1-eip-191')
Supportive of the shorter form as well for conciseness reasons as well. Thanks for digging in!

2022-07-18 19:49 UTC, varunsrin requested changes

2022-07-18 19:49 UTC, varunsrin commented on src/sets/verificationsSet.test.ts
> +      describe('with same timestamp', () => {
good point. in that case, i think we should explicitly fail non EIP 191 signatures, either in the set or the engine. it prevents downstream clients from having to test for both.

2022-07-18 20:18 UTC, pfletcherhill commented on src/sets/verificationsSet.test.ts
> +      describe('with same timestamp', () => {
So now that we're restricting it to EIP 191 version `0x45`, all valid external signatures of the same claim should be identical. Do you think it's better to remove this test and the block in `VerificationSet` that handles it? Or leave it knowing there may be a future change (supporting more external signature types) that makes it relevant again?

2022-07-19 03:51 UTC, varunsrin approved these changes

2022-07-19 03:52 UTC, merged