Ad/misc utils
farcasterxyz/hub pull request #378
Opened 2023-01-04 02:01 UTC by adaddeo

## Motivation

Two small util additions that will constructing messages easier.

## Change Summary

- add `utils/ed25519` to provide `HubResult` convenience functions around `ed` functions
- introduces classes for EthereumSigner and Ed25519Signer that implement a Signer interface (backwards compatible with a `sign` function added)

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)

## Additional Context

These came out of the work I was doing on #355. I'm ok to take one, both, or none of the commits.

2023-01-04 03:04 UTC, pfletcherhill requested changes
Overall, I think it's a good idea to refactor the signers and crypto utils. The way they're organized now is pretty awkward and largely a relic of a time before flatbuffers. To that end, I think we can make the refactor more dramatic and not worry about backwards compatibility, and I've left some comments and suggestions to that effect. If we're adding these classes, we should use them everywhere rather than continuing to rely on `KeyPair` in many places.

2023-01-04 15:03 UTC, adaddeo commented on app/src/utils/signer/ethereumSigner.ts
> +  public scheme = SignatureScheme.Eip712;
yes thats better

2023-01-04 21:56 UTC, adaddeo commented
@pfletcherhill incorporated your feedback

- `Signers` only need a privateKey, everything else is derived
- `generate*` functions are gone and replaced with `Factories.Eip712Signer` and `Factories.Ed25519Signer`
- `ethers.Wallet` dependency removed from `Factories` and nearly all tests

2023-01-05 02:45 UTC, adaddeo commented on app/src/signers/eip712Signer.ts
> +    const signerKey = hexStringToBytes(wallet.address.toLowerCase())._unsafeUnwrap();
Ah! right, I'll open up a new pr with the fix

2023-01-05 04:22 UTC, merged