[feature] Add SignerSet implementation
farcasterxyz/hub pull request #38
Opened 2022-07-21 18:25 UTC by pfletcherhill

Updated version of SignerSet implementation. Original work done by @drshrey.

2022-07-28 00:12 UTC, varunsrin commented on src/sets/signerSet.ts
> +      if (!this._vertices.has(childPubKey)) {
should we also check that the child doesn't exist in custodySigners?

2022-07-28 14:57 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  private get _vertices() {
Fair enough. I was undecided about where to put private getters, but I can move them down.

2022-07-28 15:15 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  for Signing and their corresponding delegates.
Added summary at top of set

2022-07-28 15:15 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  mergeSignerAdd(message: SignerAdd): Result<void, string> {
Made these private in favor of just using `merge`

2022-07-28 15:19 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +    const byChildMap = new Map<string, Set<string>>();
Ah sloppy me

2022-07-28 15:22 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  private add(parentPubKey: string, childPubKey: string, hash: string): Result<void, string> {
I'd prefer to keep it `add`, because I have a `removeEdge` method below that takes an edge key (tuple string) as argument. And the `add` and `remove` methods add and remove both vertices and edges, not just edges.

2022-07-28 15:35 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  private getEdgesByChild(edges: Map<string, string>) {
Good call, adding comment

2022-07-28 15:42 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +        // Get all parents of parentPubKey by traversing edgeAdds
Added comment

2022-07-28 15:57 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +      if (!this._vertices.has(childPubKey)) {
Oh this brings up an interesting edge case...what happens when the same key is added as a custody signer on one hub and as a delegate on another hub? We don't currently handle that conflict.

2022-07-28 16:29 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  private get _edgeAddsByChild() {
Hmm `_edgeAddsByChild` makes more sense to me, since it's the result of `getEdgesByChild`. And `AllChildren` implies all children in both adds and removes to me.

2022-07-28 18:53 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +      if (!this._vertices.has(childPubKey)) {
Okay, upon thinking about this more...
* Custody signers will be identified using addresses (20 bytes) rather than public keys, right? Because we'll look at the `msg.sender` in the account registry contract.
* Delegate signers now are identified using their public keys (32 bytes)
* If we keep this distinction—custody signers are addresses, delegate signers are public keys—we won't have conflicts between the two

2022-07-28 20:55 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +    const parentPubKey = message.signer;
Based on our discussion before, this will be the custody's address. So I may rename this to `parentKey` to be slightly less confusing.

2022-07-29 22:41 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +      if (!this._vertices.has(childPubKey)) {
This PR addresses this https://github.com/farcasterxyz/hub/pull/50

2022-07-30 18:36 UTC, varunsrin requested changes
One concern I have is that the test suite isn't exhaustive because there are so many little edge cases - I'll try to do another pass on this before we merge

2022-07-30 18:36 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +      expect(vRems()).toEqual(new Set());
do we expect the edge to be retained here?

2022-07-30 18:36 UTC, varunsrin commented on src/factories.ts
> +  MessageSigner,
nit: message signer isn't used here

2022-07-30 18:36 UTC, varunsrin commented on src/utils.ts
> +export const generateEthereumSigner = async (): Promise<EthereumSigner> => {
nit: might be worth adding a comment about this being an ECDSA signature that follows EIP-191

2022-07-30 18:36 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +    });
another case: `a child is added by 2 different parents and then deleted by 2 different parents`

addA, addBChildOfA, addCChildofA, addDChildOfB, addDChildOfC, remDChildofB, remDChildOfC

2022-07-30 18:36 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +    });
another case: `a remove that is added within a sub-tree after the sub-tree has been removed` 

addA, addBChildOfA, addCChildofB, remBChildOfA, addDChildofC

2022-07-30 18:36 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +    test('succeeds when child has already been deleted by another parent and moves new edge to edgeRemoves', () => {
test case `a child is added into a subtree that was removed`

addA, addBChildOfA, addCChildofB, remA

2022-07-30 18:36 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +      expect(set.merge(remCFromA).isOk()).toBe(true);
should we also test that changing the order converges to the same state? or is that implicitly covered elsewhere?

addA -> remCFromA -> addCToA -> addB

2022-07-30 18:36 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +    });
another case: `a child is removed after its parent has already been removed` 

addA, addBChildOfA, addCChildofB, remBChildOfA, remCChildOfB

2022-07-30 19:14 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  getEdgeKey(parentPubKey: string, childPubKey: string): string {
Let's default to using lowercased versions—it's easier to convert to lowercase rather than convert to checksum case. I just made that change [here](https://github.com/farcasterxyz/hub/pull/50/commits/99eb20f4f13149a221977f1ef4a44166b17d3ed1) for verifying messages and will make the edge keys lowercased in the signer set as well.

2022-07-30 19:30 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +    expect(custodySigners()).toContain(custody1);
Sure, changing to `toEqual(...)`

2022-07-30 20:04 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +          expect(set.merge(addCToADuplicateFail).isOk()).toBe(true);
Yeah, good catch

2022-07-30 20:19 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +      expect(vRems()).toEqual(new Set());
The edge from `remC`? No, because it's not a valid edge (yet) and the remove message doesn't contain enough info to verify whether it is valid or invalid.

2022-07-31 03:31 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +      expect(set.merge(remCFromA).isOk()).toBe(true);
addA -> remCFromA -> addCToA -> addB will not match addA -> addCToA -> addB -> remCFromA, because c has to exist before it can be removed. That failure is covered in another test (`"fails when child hasn't been added yet"`)

2022-07-31 03:31 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +    test('succeeds when child has already been deleted by another parent and moves new edge to edgeRemoves', () => {
Added test

2022-07-31 03:31 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +    });
Added tests for all of these

2022-07-31 03:32 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +          expect(vAdds().size).toEqual(3);
Updated tests to check for specific values of vAdds, vRems, eAdds, eRems, and messages for each test

2022-07-31 03:33 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +          expect(vAdds().size).toEqual(3);
Updated

2022-07-31 03:57 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +});
Yeah, added

2022-08-01 14:54 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +    test('succeeds and removes subtree', () => {
Updated with additional descendants and a peer B that is not removed

2022-08-01 17:40 UTC, pfletcherhill commented
Summary of changes since last review:
* Expand signer set test suite to check full state (i.e. `vAdds`, `vRems`, `eAdds`, `eRems`, and `messages`) after every test
* Add tests for all the cases mentioned in @varunsrin's review
* Add explanatory comments to signer set file and methods
* Update cycle prevention logic to only reject adds that would beat out other edges and cause a cycle in eAdds
* Add more cycle tests
* Support removing custody addresses
* Sanitize keys coming from all public methods, so we always use lowercase versions in signer set

2022-08-11 19:29 UTC, varunsrin reviewed
completed review on `addCustody` method

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +describe('addCustody', () => {
a case that is currently uncovered by tests: 

- block 1: custody A is added
- block 2: custody B is added
- block 3: custody B removes custody A with a RemoveAll
- block 4: custody A is added again  

this tests line 122 in signerSet `this._custodyRemoves.delete(sanitizedAddress);`

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +  test('succeeds (no-ops) with a duplicate custody address', () => {
nit: maybe 'succeeds idempotently with a duplicate custody address' ?

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.ts
> +  addCustody(event: CustodyAddEvent): Result<void, string> {
it is confusing that `addCustody` and `merge` are semantically equivalent operations with different names

why merge in one place vs add<Item> in the other?

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.ts
> +    const existingCustodyRemove = this._custodyRemoves.get(sanitizedAddress);
nit: should we use `Rem` and `Rems` instead of `Remove` and `Removes` everywhere? brevity might make the code easier to read

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.ts
> +    if (existingCustodyAdd) {
nit: it may be slightly clearer if we combined these clauses into a single statement and expanded on the comment. something like: 

```ts
   // If the incoming add operation is an earlier block or the same block as the prior add operation, ignore it
    if (priorCustodyAdd && priorCustodyAdd.blockNumber >= event.blockNumber) {
       return ok(undefined);
    }

```

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.ts
> +        // If existing block number wins (same or greater block), no-op
more details here would be helpful to readers

```suggestion
        // If the incoming add operation adds an address that was previously removed
        // and if the address that performed the remove operation is more recent than the incoming add operation
        // do nothing
```

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.ts
> +      if (existingCustodyAddEvent) {
i assume it is impossible to be in the state `existingCustodyRemove && ! existingCustodyAddEvent == true?` because if the addevent was removed then the remove event should also be removed?

if so, should we be throwing? because it seems like we will just ignore this case right now

2022-08-11 19:29 UTC, varunsrin commented on src/sets/signerSet.ts
> +        // If new block number wins, remove address from removes
expanding on this comment in the prior style might also be helpful

2022-08-11 19:33 UTC, varunsrin commented
@pfletcherhill the coverage report here also shows a few untested lines in other functions that are probably worth adding coverage to: https://app.codecov.io/gh/farcasterxyz/hub/compare/38/tree/src/sets/signerSet.ts

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +   * mergeCustodyRemoveAll moves all address in custodyAdds with a block number before the
nit: `addresses`

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +   * @param message - CustodyRemoveAll message
nit: we should either remove this or specify more detail like `signed message that indicates that all prior custody addresses should be removed from the valid set`

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +    const sanitizedAddress = sanitizeSigner(message.signer);
nit: should we just call this `lowerCaseAddress` instead? clearer about what it does

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +    const sanitizedAddress = sanitizeSigner(message.signer);
similar nit about just calling `message.signer.toLowerCase()` instead of `sanitizeSigner(message.signer)` which is just as verbose but less clear about what its doing

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +    // If custodyAddress exists in custodyRemoves, no-op
the comment is so similar to the logic that it doesn't really add much here. 

maybe something like `If the address that requested the remove all been removed by another another remove all message, do nothing`

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +    // If custodyAddress does not exist in custodyAdds, fail
`if the add message for this custody address was never received, fail the operation`

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +    // For each custody address, remove if block number is before signer
`Remove each custody address and their child delegate signers where the custody address if the custody address was from a block that preceeds the block in which this signer became a custody address`

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +    // For each custody address, remove if block number is before signer
add an explicit note about how we don't care about events in the same block

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.ts
> +        // Drop all SignerAdd messages signed by the custody address being removed
add a note about why its a drop and not a move into the remove set

2022-08-11 22:42 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +      test('succeeds and removes signers added by removed custody address', () => {
nit: `succeeds and drops signers`

2022-08-11 22:45 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +      test('succeeds and removes signers added by removed custody address', () => {
nit: `succeeds and drops signers`

2022-08-11 22:45 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +
test case:  add signers, remove signers and then remove the custody address and test that the removes were dropped as well

2022-08-11 22:45 UTC, varunsrin commented on src/sets/signerSet.test.ts
> +
test case:  add custody address A, do a rem all from A, then add B, do a rem all from B and assert that the rem all from A was dropped

2022-08-11 22:53 UTC, varunsrin commented on src/sets/signerSet.ts
> +    // If custody address has been removed, no-op
`If the custody address that authorized the signer has been removed by another operation, do nothing`

2022-08-11 22:53 UTC, varunsrin commented on src/sets/signerSet.ts
> +    // If custody address is missing, fail
`If the custody address that authorized the signer was never added, do nothing`

2022-08-11 22:53 UTC, varunsrin commented on src/sets/signerSet.ts
> +          if (
can we do this more deterministcally by requiring a transactionId and logIndex to be passed in along with the block? 

that way we can determine exactly which custodyAdd event wes later and choose accordingly

2022-08-12 15:33 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +describe('addCustody', () => {
Adding

2022-08-12 15:34 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  addCustody(event: CustodyAddEvent): Result<void, string> {
Updated

2022-08-12 15:41 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +    const existingCustodyRemove = this._custodyRemoves.get(sanitizedAddress);
Eh I'm on the fence about this one. I went with "remove" because the remove types (`CastRemove` `VerificationRemove`, etc) will always have it spelled out, and I thought the sets should be consistent. But I could go either way...

2022-08-12 15:43 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +    if (existingCustodyAdd) {
fwiw I think "existing" is better than "prior" because when we define that variable we don't know whether it is prior or not, just that it exists or doesn't

2022-08-12 16:09 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +  merge(message: SignerMessage | CustodyRemoveAll): Result<void, string> {
See comment here https://github.com/farcasterxyz/hub/pull/38/#discussion_r944584009

2022-08-12 17:32 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +    const sanitizedAddress = sanitizeSigner(message.signer);
Added a comment from the last PR about this: https://github.com/pfletcherhill/farcaster-hub/pull/3#discussion_r942905953

If we decide to change from lowercase to uppercase for some reason, that's trivial to do if we used `sanitizeSigner` everywhere.

2022-08-12 17:53 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +
Ah this is a bug! Good catch! We should update the past remove messages to reference a later block number rather than dropping them.

2022-08-12 17:55 UTC, varunsrin commented on src/sets/signerSet.ts
> +    const sanitizedAddress = sanitizeSigner(message.signer);
ah ok fair, thats a good argument for the abstraction

2022-08-12 21:11 UTC, pfletcherhill commented on src/sets/signerSet.test.ts
> +  test('succeeds (no-ops) with a duplicate custody address', () => {
Eh I don't know. I always misspell idempotent when I'm typing it out. You definitely think it's better?

2022-08-12 21:18 UTC, pfletcherhill commented on src/sets/signerSet.ts
> +      if (existingCustodyAddEvent) {
Yeah, should be impossible. I added "unexpected state" errors here and a few other places we have a similar pattern.

2022-08-16 21:41 UTC, varunsrin approved these changes

2022-08-16 21:46 UTC, merged