test: add tests for deserialize*RegistryEvents
farcasterxyz/hub pull request #422
Opened 2023-01-13 16:08 UTC by adaddeo

## Motivation

Tests were missing for `deserializeIdRegistryEvent` and `deserializeNameRegistryEvent`.

## Change Summary

- adds tests for `deserializeIdRegistryEvent` and `deserializeNameRegistryEvent`
- improve related factories
- organize functions in `utils.ts`

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

2023-01-13 19:27 UTC, pfletcherhill requested changes
Looks good, couple minor changes

2023-01-13 19:27 UTC, pfletcherhill commented on packages/js/src/utils.ts
> +    bytesToHexString(flatbuffer.blockHashArray() ?? new Uint8Array()),
Block hash (`size: 64`), transaction hash (`size: 64`), to/from (as eth addresses) should all be fixed size hex strings and likely have their own deserialize functions so we don't have to remember the lengths elsewhere in the code. We already have `deserializeEthAddress` that ensures that the deserialized eth address is 40 chars (plus 0x).

2023-01-13 19:27 UTC, pfletcherhill commented on packages/js/src/utils.ts
> +    bytesToHexString(flatbuffer.blockHashArray() ?? new Uint8Array()),
Same comment as above about fixed size hex strings

2023-01-13 19:27 UTC, pfletcherhill commented on packages/utils/src/factories.ts
> +const TransactionHashFactory = Factory.define<string>(() => {
Nit: we're mixing factories that make byte arrays and factories that make hex strings in the same file. Would be nice to either have a separate file for factories that produce deserialized data or be able to specify the output format for each factory. Not worth trying to change in this PR, but just something to think about.

2023-01-13 20:42 UTC, adaddeo commented on packages/utils/src/factories.ts
> +const TransactionHashFactory = Factory.define<string>(() => {
hbu `Factories.TransactionHash.String.build()`? a little long but keeps things co-located

2023-01-13 20:49 UTC, adaddeo commented
@pfletcherhill feedback incorporated

2023-01-13 22:18 UTC, pfletcherhill approved these changes
A couple tiny nits, but leaving it up to you to address or not before merge

2023-01-13 22:18 UTC, pfletcherhill commented on packages/js/src/utils.test.ts
> +  const signature = bytesToHexString(signatureBytes)._unsafeUnwrap();
Nit: consider adding `{size: 130}` here just to be extra explicit. Right now this will succeed because the bytes factory always produces unpadded byte arrays, but if that code ever changes then this test will start failing every once in a while.

2023-01-13 22:18 UTC, pfletcherhill commented on packages/js/src/utils.test.ts
> +  const signature = bytesToHexString(signatureBytes)._unsafeUnwrap();
Same nit as above

2023-01-13 22:18 UTC, pfletcherhill commented on packages/utils/src/factories.ts
> +const TransactionHashFactory = Factory.define<string>(() => {
Do you think that's better than `Factories.TransactionHash` (bytes) and `Factories.TransactionHashHex`?

2023-01-13 22:18 UTC, pfletcherhill commented on packages/utils/src/factories.ts
> +const TransactionHashFactory = Factory.define<string>(() => {
Just added an issue for us to think about this more at some point https://github.com/farcasterxyz/hub/issues/425

2023-01-14 16:25 UTC, adaddeo commented on packages/js/src/utils.test.ts
> +  const signature = bytesToHexString(signatureBytes)._unsafeUnwrap();
ok finally have by head around this—all byte arrays are unpadded!

2023-01-14 16:37 UTC, merged