Add signatureType to messages
farcasterxyz/hub pull request #50
Opened 2022-07-29 20:25 UTC by pfletcherhill

Implements https://github.com/farcasterxyz/hub/issues/49

2022-07-29 20:48 UTC, pfletcherhill commented on src/engine/engine.cast.test.ts
> +    // Randomly generate either an Ed25519 or Ethereum signer
@varunsrin because it takes longer to generate and use an Ethereum signer, adding randomness like this means our test suite timing changes +/- 5 seconds based on how many test suites are using Ethereum vs Ed25519. Do you think that's okay for now, or should I default to Ed25519 and add an extra test to each engine suite that uses an Ethereum signer?

2022-07-30 18:56 UTC, varunsrin requested changes

2022-07-30 18:56 UTC, varunsrin commented on src/engine/engine.cast.test.ts
> +  // let alicePrivateKey: string;
nit: can we just eliminate this?

2022-07-30 18:56 UTC, varunsrin commented on src/engine/engine.cast.test.ts
> +    // Randomly generate either an Ed25519 or Ethereum signer
why random? all casts must be signed by Ed25519 according to our specification 

the only message types that can be signed by Ethereum signers are the SignerAdds

2022-07-30 18:56 UTC, varunsrin commented on src/engine/engine.reaction.test.ts
> +    // Randomly generate either an Ed25519 or Ethereum signer
same comment about types here

2022-07-30 19:07 UTC, pfletcherhill commented on src/engine/engine.cast.test.ts
> +    // Randomly generate either an Ed25519 or Ethereum signer
Oh I didn't realize that. I thought a custody address could sign messages as well.

2022-07-30 19:22 UTC, pfletcherhill commented on src/engine/engine.cast.test.ts
> +  // let alicePrivateKey: string;
Oops

2022-07-31 18:51 UTC, pfletcherhill commented on src/engine/engine.cast.test.ts
> +    // Randomly generate either an Ed25519 or Ethereum signer
No longer relevant

2022-07-31 18:52 UTC, pfletcherhill commented on src/engine/engine.cast.test.ts
> +    // Randomly generate either an Ed25519 or Ethereum signer
Resolved based on slack conversation. No longer generates Ethereum signers.

2022-08-01 18:32 UTC, varunsrin reviewed
Good to merge, left some small nits that can be fixed in this PR or a followup

2022-08-01 18:32 UTC, varunsrin commented on src/engine/index.ts
> +        return err('validateMessage: invalid signature');
nit: should we try to stringify the error and include it here so it makes debugging easier?

2022-08-01 18:32 UTC, varunsrin commented on src/factories.ts
> +  props: Message,
nit: why props instead of message? especially since the comment says message object too

2022-08-01 18:32 UTC, varunsrin commented
Good to merge, left some small nits that can be fixed in this PR or a followup

2022-08-01 19:25 UTC, pfletcherhill commented on src/factories.ts
> +  props: Message,
I had kept it consistent with the factories that have props and transientParams, but I don't feel strongly either way. I'll change to `message`.

2022-08-01 19:27 UTC, pfletcherhill commented on src/engine/index.ts
> +        return err('validateMessage: invalid signature');
Eventually, yeah. There's a todo in verifications to pass through more helpful error messages from `verifyMessage` too. I'm going to punt on doing that now though.

2022-08-02 00:22 UTC, merged